using Newtonsoft.Json;

namespace OCPP_RD.OCPP2._1_Models
{
    /// <summary>CS → CSMS. Requests the CSMS to sign a certificate CSR generated by the station.</summary>
    public class SignCertificateRequest
    {
        [JsonProperty("csr")]
        public string Csr { get; set; } = null!;

        [JsonProperty("certificateType")]
        public CertificateSigningUseEnumType? CertificateType { get; set; }

        [JsonProperty("requestId")]
        public int? RequestId { get; set; }

        [JsonProperty("hashRootCertificate")]
        public CertificateHashDataType? HashRootCertificate { get; set; }

        [JsonProperty("customData")]
        public CustomDataType? CustomData { get; set; }
    }

    public class SignCertificateResponse
    {
        [JsonProperty("status")]
        public GenericStatusEnumType Status { get; set; }

        [JsonProperty("statusInfo")]
        public StatusInfoType? StatusInfo { get; set; }

        [JsonProperty("customData")]
        public CustomDataType? CustomData { get; set; }
    }
}
