// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OCPPServer.Data;

#nullable disable

namespace OCPPServer.Migrations
{
    [DbContext(typeof(ChargingDBContext))]
    [Migration("20260525151613_MigrateToPlugs")]
    partial class MigrateToPlugs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OCPPServer.DataBase.DBModels.Plug", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChargePointModel")
                        .HasColumnType("text");

                    b.Property<string>("ChargePointSN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirmwareVersion")
                        .HasColumnType("text");

                    b.Property<bool>("IsFastCharger")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastMeterValueAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastStatusUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxPower")
                        .HasColumnType("integer");

                    b.Property<decimal?>("MeterValue")
                        .HasColumnType("numeric");

                    b.Property<string>("OcppId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OcppVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SIMNr")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Vendor")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Plugs");
                });
#pragma warning restore 612, 618
        }
    }
}
