// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OCPPServer.Data;

#nullable disable

namespace OCPPServer.Migrations
{
    [DbContext(typeof(ChargingDBContext))]
    [Migration("20260520185609_RemoveOrphanTables")]
    partial class RemoveOrphanTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OCPPServer.DataBase.DBModels.Connector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActiveTransactionId")
                        .HasColumnType("integer");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("ChargePointModel")
                        .HasColumnType("text");

                    b.Property<string>("ChargePointSN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ChargerSN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("CurrentPowerKw")
                        .HasColumnType("double precision");

                    b.Property<string>("FirmwareVersion")
                        .HasColumnType("text");

                    b.Property<bool>("IsFastCharger")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastMeterValueAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("MaxPowerKw")
                        .HasColumnType("double precision");

                    b.Property<decimal?>("MeterStart")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("MeterStop")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("MeterValue")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("NumberOfConnectors")
                        .HasColumnType("integer");

                    b.Property<string>("OcppId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SIMNr")
                        .HasColumnType("text");

                    b.Property<DateTime?>("SessionStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("ShowOnMap")
                        .HasColumnType("boolean");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Vendor")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Connectors");
                });
#pragma warning restore 612, 618
        }
    }
}
