// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OCPPServer.Data;

#nullable disable

namespace OCPPServer.Migrations
{
    [DbContext(typeof(ChargingDBContext))]
    [Migration("20260518224621_AddNumberOfConnectors")]
    partial class AddNumberOfConnectors
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OCPPServer.ChargingStationInterface.ChargingSessionInfo", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("ConnectorId")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentBatteryPercentage")
                        .HasColumnType("integer");

                    b.Property<decimal>("CurrentPowerDelivery")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("EnergyConsumed")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PrepaidAmount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TagId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("numeric");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("SessionId");

                    b.HasIndex("ConnectorId");

                    b.HasIndex("UserId");

                    b.ToTable("ChargingSessions");
                });

            modelBuilder.Entity("OCPPServer.DataBase.DBModels.ChargingStation", b =>
                {
                    b.Property<string>("ChargerSN")
                        .HasColumnType("text");

                    b.Property<int>("LocationId")
                        .HasColumnType("integer");

                    b.Property<decimal>("MeterValue")
                        .HasColumnType("numeric");

                    b.Property<int>("NOfConnectors")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ChargerSN");

                    b.HasIndex("LocationId");

                    b.ToTable("ChargingStations");
                });

            modelBuilder.Entity("OCPPServer.DataBase.DBModels.Connector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("ChargePointModel")
                        .HasColumnType("text");

                    b.Property<string>("ChargePointSN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ChargerSN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ChargingStationChargerSN")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirmwareVersion")
                        .HasColumnType("text");

                    b.Property<bool>("IsFastCharger")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("MaxPowerKw")
                        .HasColumnType("double precision");

                    b.Property<decimal?>("MeterValue")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("NumberOfConnectors")
                        .HasColumnType("integer");

                    b.Property<string>("OcppId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SIMNr")
                        .HasColumnType("text");

                    b.Property<bool>("ShowOnMap")
                        .HasColumnType("boolean");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Vendor")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChargingStationChargerSN");

                    b.ToTable("Connectors");
                });

            modelBuilder.Entity("OCPPServer.DataBase.DBModels.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LocationId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GPSLocation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LocationId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("OCPPServer.DataBase.DBModels.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("EVId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("OCPPServer.ChargingStationInterface.ChargingSessionInfo", b =>
                {
                    b.HasOne("OCPPServer.DataBase.DBModels.Connector", "Connector")
                        .WithMany()
                        .HasForeignKey("ConnectorId");

                    b.HasOne("OCPPServer.DataBase.DBModels.User", "User")
                        .WithMany("ChargingSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Connector");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OCPPServer.DataBase.DBModels.ChargingStation", b =>
                {
                    b.HasOne("OCPPServer.DataBase.DBModels.Location", "Location")
                        .WithMany("ChargingStations")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("OCPPServer.DataBase.DBModels.Connector", b =>
                {
                    b.HasOne("OCPPServer.DataBase.DBModels.ChargingStation", "ChargingStation")
                        .WithMany("Connectors")
                        .HasForeignKey("ChargingStationChargerSN");

                    b.Navigation("ChargingStation");
                });

            modelBuilder.Entity("OCPPServer.DataBase.DBModels.ChargingStation", b =>
                {
                    b.Navigation("Connectors");
                });

            modelBuilder.Entity("OCPPServer.DataBase.DBModels.Location", b =>
                {
                    b.Navigation("ChargingStations");
                });

            modelBuilder.Entity("OCPPServer.DataBase.DBModels.User", b =>
                {
                    b.Navigation("ChargingSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
